# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule: 
    - cron: "0 1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.PAT }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Pull us states data
      run: |
        export covid_s3_access_key=${{ secrets.COVID_S3_ACCESS_KEY }}
        export covid_s3_token=${{ secrets.COVID_S3_TOKEN }}
        export bucket_name=${{ secrets.BUCKET_NAME }}
        export data_file=${{ secrets.DATA_FILE }}
        python risk_calculator_cases_deaths.py
    - name: Push changes to us states
      run: |
          git config --global user.name 'pawan-nandakishore'
          git config --global user.email 'pawan.nandakishore@gmail.com'
          git add .
          git commit --allow-empty -am "Automated report for us states only"
          git push
    - name: Pull world data
      run: |
        export covid_s3_access_key=${{ secrets.COVID_S3_ACCESS_KEY }}
        export covid_s3_token=${{ secrets.COVID_S3_TOKEN }}
        export bucket_name=${{ secrets.BUCKET_NAME }}
        export data_file=${{ secrets.DATA_FILE }}
        python risk_calculator_data.py
    - name: Push changes world data
      run: |
          git config --global user.name 'pawan-nandakishore'
          git config --global user.email 'pawan.nandakishore@gmail.com'
          git add .
          git commit --allow-empty -am "Automated report for world covid data "
          git push

